Experiment 1

    Study of Numpy and Pandas Library in Python

Install numPy

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


Importing numPy Library

In [5]:
import numpy as np
import pandas as pd

Create a 1-D array A

In [6]:
A = np.array([1,2,3,4,5,6,7,8,9])

Print Elements and type of A

In [7]:
print(A)
print(type(A))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


Create 2-D array B. Print its element and type.

In [9]:
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(B)
print(type(B))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


Create 3-D array C. Print its element and type

In [13]:
C = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(C)
print(type(C))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
<class 'numpy.ndarray'>


Print 3rd element of A

In [14]:
print(A[3])

4


Print 2nd element of 3rd row of B

In [15]:
print(B[2,1])

8


Print 1st element of 2nd array of the 2nd array of C

In [18]:
print(C[2,1,1])

12


Print Last elements of C

In [19]:
print(C[-1,-1,-1])

12


Slice elements from index 1 to 5 of A

In [20]:
print(A[1:5])

[2 3 4 5]


Slice elements from the beginning to 4th element of A

In [21]:
print(A[:5])

[1 2 3 4 5]
