# Support Vector Machine Using Scikit Learn

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler 

In [4]:
exp7 = pd.read_csv('Social_Network_Ads.csv')

X = exp7.iloc[:, [2, 3]].values
y = exp7.iloc[:, 4].values

exp7.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [19]:
exp7['Purchased'].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [7]:
sc = StandardScaler() 
X_train = sc.fit_transform(X_train) 
X_test = sc.fit_transform(X_test) 

## Kernel as Linear

In [28]:
classifier = SVC(kernel='linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [29]:
y_pred1 = classifier.predict(X_test)

In [30]:
scoreee = classifier.score(X_test, y_test)
print("Accuracy using SVM : ",scoreee)
print(confusion_matrix(y_test, y_pred1))

Accuracy using SVM :  0.88
[[63  5]
 [ 7 25]]


## Kernel as Poly

In [11]:
classifier = SVC(kernel='poly', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='poly', random_state=0)

In [12]:
y_pred2 = classifier.predict(X_test)

In [13]:
scoreee = classifier.score(X_test, y_test)
print("Accuracy using SVM : ",scoreee)
print(confusion_matrix(y_test, y_pred2))

Accuracy using SVM :  0.84
[[64  4]
 [12 20]]


## Kernel as rbf

In [14]:
classifier = SVC(kernel='rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [15]:
y_pred3 = classifier.predict(X_test)

In [16]:
scoreee = classifier.score(X_test, y_test)
print("Accuracy using SVM : ",scoreee)
print(confusion_matrix(y_test, y_pred3))

Accuracy using SVM :  0.93
[[64  4]
 [ 3 29]]
